### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by sammygriffiths** [aerocommerce/cli#11]
Since #10 was merged the install fails with
```bash
ErrorException  : symlink(): No such file or directory

  at /Users/sammy/Projects/aero-commerce/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252
    248|      */
    249|     public function link($target, $link)
    250|     {
    251|         if (! windows_os()) {
  > 252|             return symlink($target, $link);
    253|         }
    254|
    255|         $mode = $this->isDirectory($target) ? 'J' : 'H';
    256|

  Exception trace:

  1   symlink("/Users/sammy/Projects/aero-commerce/vendor/aerocommerce/admin/public", "/Users/sammy/Projects/aero-commerce/public/vendor/aerocommerce/admin")
      /Users/sammy/Projects/aero-commerce/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:252

  2   Illuminate\Filesystem\Filesystem::link("/Users/sammy/Projects/aero-commerce/vendor/aerocommerce/admin/public", "/Users/sammy/Projects/aero-commerce/public/vendor/aerocommerce/admin")
      /Users/sammy/Projects/aero-commerce/vendor/aerocommerce/core/src/Store/Commands/LinkCommand.php:73

  Please use the argument -v to see more details.
Script @php artisan aero:link --ansi handling the post-autoload-dump event returned with error code 1
```

I believe this is because `php artisan aero:link` will need to be run after `aero:install` and `aero:configure`. I think, therefore, `aero:link` should probably be moved to either `aero:install` or `aero:configure`.

**Comment by timrspratt** [comment]
`aero:link` should run as a post composer dumpautoload, so in theory should have ran after the cli new command

**Comment by timrspratt** [comment]
Actually, it's because public/vendor/aerocommerce doesn't exist. It is a directory that is popped in when aero:install runs. When we have our own base project starting point, we can include this directory (and it's own .gitignore), so for now the cli should probably add this directory in

**Comment by andrewnclark** [comment]
I imagine this is something that will change again when we get around to this bootstrapper thing?

**Comment by sammygriffiths** [comment]
@andrewnclark Yea I'd imagine so.
